name: green_cart
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1
  curved_navigation_bar: ^1.0.6
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  dio: ^5.9.0
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/images/banners/
    - assets/images/groceries/
    # >> categories
    - assets/images/categories/vegetables/
    - assets/images/categories/meat/
    - assets/images/categories/fruits/
    - assets/images/categories/dairy/
    - assets/images/icons/




  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
